### Tensors

Specialized data structures, similae to arrays and matrices, used to encode inputs and outputs of a model, as well as the model's parameters.

Similar to Numpy's ndarrays, that can run on GPUs or other hardware accelerators.

Tensors and ndarrays can even share the same underlying memory (avoiding copying data).

Tensors are optimized for automatic differentiation

In [1]:
import torch
import numpy as np

###### Initializing a Tensor

In [2]:
# from data
data   = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
#print(f"Data Tensor: \n {x_data} \n")

# from numpy array
np_array = np.array(data)
x_np     = torch.from_numpy(np_array) 
#print(f"Numpy Array Tensor: \n {x_np} \n")

# from another tensor 
x_ones = torch.ones_like(x_data) # retains properties of x_data
#print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) #overrides datatype of x_data
#print(f"Random Tensor: \n {x_rand} \n")

# with random or constant values
shape = (2,3,) # tuple of thesor dimentions (determines dimentionality of output tensor)
rand_tensor  = torch.rand(shape)
ones_tensor  = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.2202, 0.0780, 0.2963],
        [0.8556, 0.2261, 0.7313]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



###### Attributes of a Tensor

Describe their shape, datatype, and device on which they are stored.

In [3]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


###### Operations on Tensors

Over 100 tensor operations, described [here](https://pytorch.org/docs/stable/torch.html), each can be run on the GPU.

By default, tensors are created on the CPU, they need to be explicitly moved to the GPU using <code>.to</code> method (copying large tensors can be expensive).



In [4]:
# Move tensor if GPU is available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [5]:
# standard numpy-like indexing and slicing
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column: ', tensor[..., -1])

tensor[:,1]=0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [6]:
# joining tensors torch.cat 
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [7]:
# Matrix multiplication between 2 tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [8]:
# element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [9]:
# single-element tensors, can be convertes to python numerical value using item()
agg = tensor.sum()
agg_item = agg.item()

print(agg_item, type(agg_item))

12.0 <class 'float'>


In [10]:
# in-place operations operations that store the result into the operand are called in-place
# denoted by a _ suffix (x.copy_(y), x.t_() will change x)
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In-place operations save memory, but can be problematic when computing derivatives, due to immediate loss of history. Hence, their use is discouraged

###### Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [11]:
# tensor to NumPy array
t = torch.ones(5)
print(f"t:{t}")
n = t.numpy()
print(f"n: {n}")

t:tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [12]:
# a change in the tensor reflects in the np array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [13]:
# numpy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)

In [14]:
# changes in np array reflects in tensor
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
